type = "file"
name = "Twitter1"
capacities = [ 250, 500, 750, 1000, 1250, 1500, 1750, 2000 ]
caches = [
    "otter",
    "theine",
    "ristretto",
    "lru",
    "arc"
]

[file]
trace_type = "oracleGeneral"
paths = [ "trace/oracleGeneral/cluster45.oracleGeneral.sample10.zst" ]
